// electron-builder configuration for ChemThisTry.
// Docs: https://www.electron.build/configuration/configuration
//
// Build the app first (`npm run build` → out/{main,preload,renderer}), then run
// one of the `dist:*` scripts, which invoke electron-builder with this file.
//
// macOS code signing / notarization:
//   - Signing is automatic once a "Developer ID Application" certificate is
//     present in the login keychain (or CSC_LINK / CSC_KEY_PASSWORD are set).
//     Without credentials electron-builder produces an unsigned build.
//   - Notarization is OFF by default. Enable it by setting CTT_NOTARIZE=true
//     together with APPLE_ID / APPLE_APP_SPECIFIC_PASSWORD / APPLE_TEAM_ID.
//     (The CI workflow sets CTT_NOTARIZE only when an Apple ID secret exists,
//     so PRs / forks still build unsigned without failing.)

const notarize = process.env.CTT_NOTARIZE === 'true'

// Refuse to cross-build the Windows target from a non-Windows host. Native
// modules (better-sqlite3) cannot be compiled for win32 here, so a cross-build
// silently embeds the host's native binary, which then fails at runtime on
// Windows with "is not a valid Win32 application". The Windows package MUST be
// built on a Windows host (or the windows-latest CI runner).
if (
  process.argv.includes('--win') &&
  process.platform !== 'win32' &&
  !process.env.CTT_ALLOW_CROSSBUILD
) {
  console.error(
    '\n[electron-builder] Refusing to build the Windows target from a non-Windows host.\n' +
      '  Native modules (e.g. better-sqlite3) cannot be cross-compiled for win32 here,\n' +
      '  which would ship a macOS/Linux binary that fails on Windows with\n' +
      '  "is not a valid Win32 application".\n' +
      '  -> Build the Windows installer on a Windows machine, or let the CI\n' +
      '     windows-latest job produce it (push a "v*" tag or run the workflow\n' +
      '     manually). Set CTT_ALLOW_CROSSBUILD=1 only if you know what you are doing.\n'
  )
  process.exit(1)
}

const fs = require('fs')
const path = require('path')

// The Windows build can optionally bundle a self-contained Python runtime so end
// users don't have to install Python themselves. Populate `resources/python`
// (e.g. via `node scripts/bundle-python-win.mjs` on a Windows build host) and it
// will be copied into the app automatically; chemSidecar.ts resolves it first.
// Skipped when the directory is absent, so non-Windows and dev builds are unaffected.
const extraResources = [
  { from: 'electron/chem_sidecar.py', to: 'chem_sidecar.py' },
  // Pyodide (local, offline Python). Copied out of app.asar so the renderer can
  // fetch it via the in-app `cttpy://` protocol. Generated by
  // `scripts/fetch-pyodide.mjs` into pyodide-dist/ at build time.
  { from: 'pyodide-dist', to: 'pyodide' },
]
const winPythonDir = path.join(__dirname, 'resources', 'python')
if (process.platform === 'win32' && fs.existsSync(winPythonDir)) {
  extraResources.push({ from: winPythonDir, to: 'python' })
}

/** @type {import('electron-builder').Configuration} */
module.exports = {
  appId: 'cn.chemthistry.app',
  productName: 'ChemThisTry',
  copyright: 'Copyright © 2026 ChemThisTry Team',

  // Where electron-builder writes installers/artifacts.
  directories: {
    output: 'release',
    buildResources: 'build',
  },

  // Application icon (no extension — electron-builder resolves .icns on macOS,
  // .ico on Windows, .png on Linux from the buildResources directory).
  icon: 'build/icon',

  // What goes INSIDE the app bundle (packed into app.asar). The renderer, main
  // and preload all live under out/ after `npm run build`.
  files: ['out/**/*', 'package.json'],

  // The Python sidecar must live OUTSIDE app.asar so an external Python process
  // can read/execute it. It is copied to <resources>/chem_sidecar.py and located
  // at runtime via process.resourcesPath (see electron/chemSidecar.ts).
  extraResources,

  // better-sqlite3 ships a native .node binary; it must be unpacked from the
  // asar so the dynamic loader can find it at runtime.
  asar: true,
  asarUnpack: ['**/node_modules/better-sqlite3/**'],

  // ---- macOS ---------------------------------------------------------------
  mac: {
    category: 'public.app-category.education',
    target: [
      { target: 'dmg', arch: ['arm64', 'x64'] },
      { target: 'zip', arch: ['arm64', 'x64'] },
    ],
    // Hardened runtime + entitlements are required for notarization. Signing is
    // opt-in: a local keychain identity (or CSC_LINK / CSC_KEY_PASSWORD) is
    // needed. Without credentials electron-builder produces an unsigned build.
    //
    // `identity` is driven by CSC_NAME so you can force a specific certificate
    // when auto-detection reports "no signing info identified" (e.g. the login
    // keychain isn't in `security list-keychains`, or the build runs in a context
    // that can't read it). Leave CSC_NAME unset to auto-discover.
    //   CSC_NAME="SIYANG LI (2X96566LVB)" npm run dist:mac
    //   (No "Developer ID Application:" prefix — electron-builder adds the
    //    type automatically and picks the matching cert.)
    hardenedRuntime: true,
    gatekeeperAssess: false,
    entitlements: 'build/entitlements.mac.plist',
    entitlementsInherit: 'build/entitlements.mac.plist',
    identity: process.env.CSC_NAME || undefined,
    // Set CTT_NOTARIZE=true (and provide APPLE_* creds) to notarize. Kept false
    // so unsigned local/CI builds still succeed.
    notarize,
  },

  dmg: {
    contents: [
      { x: 130, y: 220 },
      { x: 410, y: 220, type: 'link', path: '/Applications' },
    ],
  },

  // ---- Windows -------------------------------------------------------------
  win: {
    target: [{ target: 'nsis', arch: ['x64', 'arm64'] }],
    // Code signing (optional): provide WIN_CSC_LINK / WIN_CSC_KEY_PASSWORD.
  },

  nsis: {
    oneClick: false,
    perMachine: false,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
  },

  // ---- Linux ---------------------------------------------------------------
  linux: {
    category: 'Education',
    target: ['AppImage', 'deb'],
    maintainer: 'ChemThisTry Team',
  },

  // Do NOT auto-publish; releases are attached explicitly by the CI workflow.
  publish: null,
}
