// electron-builder configuration for ChemThisTry.
// Docs: https://www.electron.build/configuration/configuration
//
// Build the app first (`npm run build` → out/{main,preload,renderer}), then run
// one of the `dist:*` scripts, which invoke electron-builder with this file.
//
// macOS code signing / notarization:
//   - Signing is automatic once a "Developer ID Application" certificate is
//     present in the login keychain (or CSC_LINK / CSC_KEY_PASSWORD are set).
//     Without credentials electron-builder produces an unsigned build.
//   - Notarization is OFF by default. Enable it by setting CTT_NOTARIZE=true
//     together with APPLE_ID / APPLE_APP_SPECIFIC_PASSWORD / APPLE_TEAM_ID.
//     (The CI workflow sets CTT_NOTARIZE only when an Apple ID secret exists,
//     so PRs / forks still build unsigned without failing.)

const notarize = process.env.CTT_NOTARIZE === 'true'

// Native modules (better-sqlite3) cannot be cross-compiled for a DIFFERENT OS
// from this host. A cross-build would silently embed the host's native binary
// and then fail at runtime on the target OS with "is not a valid <platform>
// application". The Windows / Linux packages MUST be built on a matching host
// (or their dedicated CI runner). macOS builds are fine here.
//
// Map CLI target flags to the OS node.js reports for them.
const REQUESTED = []
if (process.argv.includes('--win')) REQUESTED.push('win32')
if (process.argv.includes('--mac') || process.argv.includes('--macos')) REQUESTED.push('darwin')
if (process.argv.includes('--linux')) REQUESTED.push('linux')

const crossBuild =
  REQUESTED.length > 0 && !REQUESTED.includes(process.platform) && !process.env.CTT_ALLOW_CROSSBUILD
if (crossBuild) {
  console.error(
    '\n[electron-builder] Refusing to cross-build native modules for a non-host OS.\n' +
      '  Requested target(s): ' +
      REQUESTED.join(', ') +
      '   |   host: ' +
      process.platform +
      '\n' +
      '  better-sqlite3 (and any other native module) can only be compiled for the\n' +
      '  host OS; node-gyp has no cross-compile support, so the package would ship a\n' +
      '  ' +
      process.platform +
      ' binary that fails on the target with "is not a valid <platform> application".\n' +
      '  -> Build on a matching host:\n' +
      '       Windows installer  -> run `npm run dist:win` on a Windows machine\n' +
      '       Linux  package     -> run `npm run dist:linux` on a Linux machine\n' +
      '       macOS package      -> run `npm run dist:mac` here (this host)\n' +
      '     You may also use a dedicated CI job for the target OS.\n' +
      '     Set CTT_ALLOW_CROSSBUILD=1 only if you have pre-supplied prebuilt native\n' +
      '     binaries for the target OS (otherwise the build will still fail later).\n'
  )
  process.exit(1)
}

const fs = require('fs')
const path = require('path')

// The Windows build can optionally bundle a self-contained Python runtime so end
// users don't have to install Python themselves. Populate `resources/python`
// (e.g. via `node scripts/bundle-python-win.mjs` on a Windows build host) and it
// will be copied into the app automatically; chemSidecar.ts resolves it first.
// Skipped when the directory is absent, so non-Windows and dev builds are unaffected.
const extraResources = [
  { from: 'electron/chem_sidecar.py', to: 'chem_sidecar.py' },
  // Pyodide (local, offline Python). Copied out of app.asar so the renderer can
  // fetch it via the in-app `cttpy://` protocol. Generated by
  // `scripts/fetch-pyodide.mjs` into pyodide-dist/ at build time.
  { from: 'pyodide-dist', to: 'pyodide' },
]
const winPythonDir = path.join(__dirname, 'resources', 'python')
if (process.platform === 'win32' && fs.existsSync(winPythonDir)) {
  extraResources.push({ from: winPythonDir, to: 'python' })
}

/** @type {import('electron-builder').Configuration} */
module.exports = {
  appId: 'cn.chemthistry.app',
  productName: 'ChemThisTry',
  copyright: 'Copyright © 2026 ChemThisTry Team',

  // Where electron-builder writes installers/artifacts.
  directories: {
    output: 'release',
    buildResources: 'build',
  },

  // Application icon (no extension — electron-builder resolves .icns on macOS,
  // .ico on Windows, .png on Linux from the buildResources directory).
  icon: 'build/icon',

  // File association: double-clicking a `.ctt` opens it in the app instead of
  // the OS trying to open it itself. electron-builder turns this single block
  // into the right platform primitive:
  //   - macOS  → CFBundleDocumentTypes in Info.plist (dock drop + double-click)
  //   - Windows → registry ProgID / OpenWith registration (NSIS)
  //   - Linux  → a MIME-type association in the .desktop entry
  // The matching runtime wiring lives in electron/main.ts (open-file /
  // second-instance / startup argv) and src/lib/projectIO.ts (the renderer
  // listener that calls project:load-path).
  fileAssociations: [
    {
      ext: 'ctt',
      name: 'ChemThisTry Project',
      role: 'Editor',
      icon: 'build/icon',
    },
  ],

  // What goes INSIDE the app bundle (packed into app.asar). The renderer, main
  // and preload all live under out/ after `npm run build`.
  files: ['out/**/*', 'package.json'],

  // The Python sidecar must live OUTSIDE app.asar so an external Python process
  // can read/execute it. It is copied to <resources>/chem_sidecar.py and located
  // at runtime via process.resourcesPath (see electron/chemSidecar.ts).
  extraResources,

  // better-sqlite3 ships a native .node binary; it must be unpacked from the
  // asar so the dynamic loader can find it at runtime.
  asar: true,
  asarUnpack: ['**/node_modules/better-sqlite3/**'],

  // ---- macOS ---------------------------------------------------------------
  mac: {
    category: 'public.app-category.education',
    target: [
      { target: 'dmg', arch: ['arm64', 'x64'] },
      { target: 'zip', arch: ['arm64', 'x64'] },
    ],
    // Hardened runtime + entitlements are required for notarization. Signing is
    // opt-in: a local keychain identity (or CSC_LINK / CSC_KEY_PASSWORD) is
    // needed. Without credentials electron-builder produces an unsigned build.
    //
    // `identity` is driven by CSC_NAME so you can force a specific certificate
    // when auto-detection reports "no signing info identified" (e.g. the login
    // keychain isn't in `security list-keychains`, or the build runs in a context
    // that can't read it). Leave CSC_NAME unset to auto-discover.
    //   CSC_NAME="SIYANG LI (2X96566LVB)" npm run dist:mac
    //   (No "Developer ID Application:" prefix — electron-builder adds the
    //    type automatically and picks the matching cert.)
    hardenedRuntime: true,
    gatekeeperAssess: false,
    entitlements: 'build/entitlements.mac.plist',
    entitlementsInherit: 'build/entitlements.mac.plist',
    identity: process.env.CSC_NAME || undefined,
    // Set CTT_NOTARIZE=true (and provide APPLE_* creds) to notarize. Kept false
    // so unsigned local/CI builds still succeed.
    notarize,
  },

  dmg: {
    contents: [
      { x: 130, y: 220 },
      { x: 410, y: 220, type: 'link', path: '/Applications' },
    ],
  },

  // ---- Windows -------------------------------------------------------------
  // x64 only: the bundled Python runtime (scripts/bundle-python-win.mjs) and
  // rdkit-pypi / MSYS2 cairo DLLs are amd64-only, so arm64 Windows builds
  // cannot ship a self-contained Python. Drop "arm64" if a future portable
  // Python becomes available.
  win: {
    target: [{ target: 'nsis', arch: ['x64'] }],
    // Code signing (optional): provide WIN_CSC_LINK / WIN_CSC_KEY_PASSWORD.
  },

  nsis: {
    oneClick: false,
    perMachine: false,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
  },

  // ---- Linux ---------------------------------------------------------------
  linux: {
    category: 'Education',
    target: ['AppImage', 'deb'],
    maintainer: 'ChemThisTry Team',
  },

  // Auto-update feed for electron-updater (bundled in the app). It reads this
  // to find new GitHub Releases and compare against the running version.
  // NOTE: macOS builds are currently UNSIGNED + un-notarized, so the app opens
  // the release page for a manual download rather than auto-installing (a
  // self-installed replacement would be quarantined by Gatekeeper). Windows
  // (NSIS) and Linux AppImage auto-install in place.
  publish: [
    {
      provider: 'github',
      owner: 'thisThisYoung',
      repo: 'ChemThisTry',
    },
  ],
}
